name: Bug
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues.
        If you find a similar issue, please comment on that issue instead of opening a new one

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?

  - type: textarea
    attributes:
      label: "Screenshots (if applicable)"
      description: "Provide any relevant screenshots."
      placeholder: "Add relevant screenshots here."

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      placeholder: "Add relevant log output here."
